### ISSUE TITLE
Virus detected in 4.0

### ISSUE THREAD

**Issue by bobcate** [bruxo00/steam-auto-shutdown#11]
Windows Security reports "Trojan:Win32/Mamson.A!ml" in version 4.0.

**Comment by gergy008** [comment]
I can confirm this as well, detected by Windows Defender

**Comment by diogomartino** [comment]
What the hell, you guys are right, it's being detected as a virus lmao: [https://www.virustotal.com/gui/file/568eecbbb02cec89240fc5d06645ce69f726d51fbc9e30d4319506cdf78aa082](https://www.virustotal.com/gui/file/568eecbbb02cec89240fc5d06645ce69f726d51fbc9e30d4319506cdf78aa082). Literally the only changes that have been made were adding some error logging, [here](https://github.com/bruxo00/steam-auto-shutdown/commit/680cf701ce2ffc0eede0797ce8ace6d4daa913cb). I guess writing to a file is dangerous lol. It's a false positive for sure. Maybe the IO reading of the steam process is triggering something? No idea. Anyways, it's open source for a reason: if you have doubts you can download the project, analyze the code and compile it. Not sure what to do about this :thinking:

**Comment by akkari93** [comment]
Think it might be worth exploring the causes further and fixing them. Windows Defender classifies the detection as "severe" which is pretty scary. People who have no or limited coding skills may be greatly discouraged. But either way the software is very helpful, thank you for putting in the time!

**Comment by diogomartino** [comment]
[Did the best I could](https://www.virustotal.com/gui/file/d4a33059fa21297546c68001bb676921fbfd5db5756248ef72cdba4a2c2f2d1c?nocache=1). Went from 19 detections including mainstream AV's like BitDefender and Karspersky to 4 detections from AV's that no one uses. Not sure if Windows Defender detects it tho. The only way to be 100% undetectable I guess is having the app digitally signed and I'm not gonna waste money on doing that. I guess it is what it is 🤷. This serves as proof on how antivirus are useless. I just changed the app GUID, the icons and now it's undetectable? Imagine if this was a real virus... 🤔

**Comment by bobcate** [comment]
Windows Security doesn't detect anything malicious anymore.
By the way, you forgot to increment the version number next to the title.

**Comment by Vojtak42** [comment]
First Kaspersky's false positive i have ever seen.
