### ISSUE TITLE
Hibernate instead of shutdown

### ISSUE THREAD

**Issue by diogomartino** [bruxo00/steam-auto-shutdown#13]
Add some kind of toggle for the user to choose if he wants to shutdown or hibernate. Should also check if hibernation is active in the system. If it is not, the option should be disabled.

**Comment by wavpro** [comment]
Added this in a proposed pull request, please check it out 😁

**Comment by diogomartino** [comment]
Hey @wavpro, thanks! Will check it out!

**Comment by diogomartino** [comment]
Feature added.
