### ISSUE TITLE
Wrong version number

### ISSUE THREAD

**Issue by dweller1907** [bruxo00/steam-auto-shutdown#14]
Donwloaded the latest version but in GUI, it still shows v4.0.

![image](https://user-images.githubusercontent.com/20239697/193657841-f7e2a976-af03-468b-8019-2cf1b2186006.png)

**Comment by diogomartino** [comment]
Hi, there is already a pull request to fix that. I haven't had the time to merge it, but it will be fixed eventually. Thanks!
