### ISSUE TITLE
Virus detected (again)

### ISSUE THREAD

**Issue by 0LUCA0** [bruxo00/steam-auto-shutdown#16]
For some weird reason Windows Detects "Trojan:AndroidOS/ZkarletFlash" but only on .zip file, it even blocks de download. After unpack all, it doesn't detect anything lol.

VirusTotal detects virus too:
https://www.virustotal.com/gui/file/7ccd35cbe63818c5f26898bc25a2d4c916c328ea1d7645477c72375f61b68cf3

**Comment by Nyalnara** [comment]
Just expanding on that: AVG triggers on it too, with `Win32:TrojanX-gen[Trj]`.

**Comment by diogomartino** [comment]
Unfortunately it's a recurring problem, see: https://github.com/diogomartino/steam-auto-shutdown/issues/11. I'll see what I can do, thanks.

But just to make it clear: it's a false positive.

**Comment by Vojtak42** [comment]
I have solution - Just use better antivirus😁.

**Comment by diogomartino** [comment]
@Vojtak42 or none at all, IMO the best antivirus is common sense. By the way, I just refactored the whole application and ported it to Wails. I hope it helps with all these antivirus issues. It is still not signed, so I don't expect any miracles.

**Comment by Vojtak42** [comment]
> so I don't expect any miracles.

There you have [miracle](https://www.virustotal.com/gui/file/8de35d57028ad66debd997c5ffd4abd45477cc997cf2b41ab399febb11541aca).

**Comment by diogomartino** [comment]
@Vojtak42 well, to be fair in the older builds at first it would also have only a few detection, but it would increase overtime. Let's hope this time it doesn't 😅
