### ISSUE TITLE
Another "false positive"

### ISSUE THREAD

**Issue by Aikoo71** [bruxo00/steam-auto-shutdown#17]
Well... Another scan that do a "false positive"

[https://www.virustotal.com/gui/file/7ccd35cbe63818c5f26898bc25a2d4c916c328ea1d7645477c72375f61b68cf3](url)

I will try to scan this in my malware lab/trivia later and update here, really awkward this giving multiple false positives...

Not accusing anyone, just weird.

**Comment by diogomartino** [comment]
Trust me, I would also be suspicious about this if it were me on your side. The thing is: there is nothing I can do about it. Sure, I can do [this](https://github.com/diogomartino/steam-auto-shutdown/commit/531c8f97f857e338bc6fca599372294e4bfd6eaf) again, and it would go another few months with no detections, but so what? It's pointless, it will happen again. This is open source for a reason. If you don't trust me, you can always check the code for yourself (it's really small, you can do it in like 5 mins) and compile it yourself. After that, you can compare your build with mine and see if there are any differences.

My best guess is: AV's don't like that an unsigned app loads a low level DLL from windows and use it to extract info about a process. If this is the case, what can I do to fix it? Apart from spending $100 in a digital certificate for the app, nothing. I also checked the [UI library](https://github.com/Taiizor/ReaLTaiizor) that this is using, and it's clean.

If you (or anyone) have any suggestions about how I can fix this, I appreciate.
