### ISSUE TITLE
Verificar uso do disco após download

### ISSUE THREAD

**Issue by ms-william** [bruxo00/steam-auto-shutdown#28]
Cara, é mais uma sugestão do que um problema. Resolvi testar a ferramenta e deixei baixando cerca de 4 jogos. Quando acordei, tinha baixado apenas 1 e meu computador tinha desligado. Creio que isso ocorreu porque a ferramenta não notou mais uso de rede no computador. Então, minha sugestão é adicionar uma verificação de disco para que, assim que um jogo terminar de baixar e verificar, o computador desligue.

**Comment by diogomartino** [comment]
Essa funcionalidade já está implementada porque já foi uma queixa no passado. No entanto, é preciso ativar manualmente em Settings (canto superior direito) > Monitor disk. Obrigado pelo feedbac!
