### ISSUE TITLE
Disk problem

### ISSUE THREAD

**Issue by ConfusedArt** [bruxo00/steam-auto-shutdown#3]
Disk detection does not work if I'm downloading on my second hard drive

any option to chose which one to detect? or detect both?(all)

**Comment by diogomartino** [comment]
It should work correctly as it's using the Steam process to monitor the disk usage, it should capture all the IO that is going on through Steam.exe.

**Comment by ConfusedArt** [comment]
i didn't know much about how it worked when i posted about this im sorry, thank you for making this it has helped me a lot!
