### ISSUE TITLE
PC wont hibernate

### ISSUE THREAD

**Issue by Vojtak42** [bruxo00/steam-auto-shutdown#32]
Hi,
I set the application to hibernate my PC after 200 second of inactivity. But when i returned, the application said that the pc will hibernate in 10 seconds but nothing was happening, it was stopped on 10 seconds. But unfortunately the app probably doesn't have any log.

**Comment by Vojtak42** [comment]
![obrazek](https://github.com/diogomartino/steam-auto-shutdown/assets/18753137/c4f21834-7882-408d-84ed-ca03298cb97a)
And nothing happens...

**Comment by Vojtak42** [comment]
When i set the inactivity time to 1 second, it works.

**Comment by diogomartino** [comment]
Do you have hibernation enabled in Windows?

**Comment by Vojtak42** [comment]
Yes, I use it regularly. After testing and restarting the app, it worked. But it's still mystery why it didn't work before.
PS Sorry for late reply

**Comment by diogomartino** [comment]
Glad it started working, no idea why it didn't before tho. Thanks for the feedback!
