### ISSUE TITLE
Detected malware on Virus total

### ISSUE THREAD

**Issue by mclarence554** [bruxo00/steam-auto-shutdown#34]
![image](https://github.com/diogomartino/steam-auto-shutdown/assets/80497598/19a62fab-8b5d-4b51-b418-2c97a610f71f)

**Comment by diogomartino** [comment]
Yes, I know about it... See #16. You have 3 options:
1. Download it and use it while trusting a random person on the internet (risky 😄)
2. Go through the code, compile the app yourself and use it securely. This is open source, to allow anyone to do that.
3. Don't use it...

Unfortunately there's nothing I can do to fix this problem. I've had this repo for 10 years (I think) and this always has been a problem.
