### ISSUE TITLE
Bkav Pro and Trapmine(Virustotal) flags this file as malicious

### ISSUE THREAD

**Issue by dzhanzakov** [bruxo00/steam-auto-shutdown#36]
https://www.virustotal.com/gui/file/8de35d57028ad66debd997c5ffd4abd45477cc997cf2b41ab399febb11541aca/detection

Could you please fix the issue, so it doesn't falsely flag this.

**Comment by diogomartino** [comment]
Yea, there's nothing I can do about that... If you see the closed issues there are a lot of them related with this.
