### ISSUE TITLE
Idle counter get's reset when too easily

### ISSUE THREAD

**Issue by Sans3108** [bruxo00/steam-auto-shutdown#4]
I've noticed that the Idle Detector counter get's reset every time there's even .1 mbps of activity, but my steam download has finished already, just came home to find that my PC was still on and drawing power but the download had finished about 7h prior to me seeing it.
My suggestion is to implement a setting where you can specify a threshold which if passed will reset the counter, otherwise just keep counting.

**Comment by diogomartino** [comment]
Thanks for your suggestion, will implement when I have time 👍
