### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by iharshraj1123** [bruxo00/steam-auto-shutdown#8]
Readme does not explain how to use this.

What exactly to open/run? i click on any file, it just opens vs code

**Comment by diogomartino** [comment]
You have two options:

- Download the source code and compile it yourself using Visual Studio
- Go to the Releases tab and download the zip file which have the binaries inside, here: [https://github.com/bruxo00/steam-auto-shutdown/releases/latest](https://github.com/bruxo00/steam-auto-shutdown/releases/tag/3.0) and execute the program normally.
